name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'

      # forms artefact from build that 'first aider' can download and use 
      - name: Run tests & capture logs
        run: |
          go test ./... 2>&1 | tee build.log

      - name: Upload build logs
        uses: actions/upload-artifact@v4
        with:
          name: build-logs     # arbitrary label
          path: build.log      # <-- this is mandatory

  first-aider:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    env:
      CLAUDE_KEY: ${{ secrets.CLAUDE_KEY }}
    if: always()
    defaults:
      run:
        working-directory: ./cmd
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build logs
        uses: actions/download-artifact@v4
        with:
          name: build-logs
          path: logs

      - name: Run First-Aider
        id: first_aider
        uses: ./
        with:
          log-path: logs/build.log
  
      - name: Post suggestion
        uses: mshick/add-pr-comment@v2
        with:
          message: ${{ steps.first_aider.outputs.comment }}
          allow-repeats: true